### ISSUE TITLE
error for two classes segmentation

### ISSUE THREAD

**Issue by zs963048949** [HiLab-git/SSL4MIS#11]
My dataset just have two classes to segmentation.When I train the dataset using your code,I got abnormal result.Could you update the code for two classes segmentation? Thanks in advanced.

**Comment by Luoxd1996** [comment]
Hi,
Sorry, your question is too rough to identify the problem. Could you describe the problem carefully and provide more details, maybe it can help us to find the problem. In addition, in my testing, it works well for two-class segmentation tasks.
Best;
Xiangde.

**Comment by zs963048949** [comment]
> Hi,
> Sorry, your question is too rough to identify the problem. Could you describe the problem carefully and provide more details, maybe it can help us to find the problem. In addition, in my testing, it works well for two-class segmentation tasks.
> Best;
> Xiangde.

Ok,Thank you. I will check the code in detail.
