### ISSUE TITLE
Comparison of 2d and 3d data

### ISSUE THREAD

**Issue by szhang963** [HiLab-git/SSL4MIS#12]
Hi,
Have you compared the result of 2D and 3D image for the same dataset, like ACDC dataset or BraTS？
Thank you in advance.
Best wish.

**Comment by Luoxd1996** [comment]
Hi,
I have some results obtained by several methods on ACDC dataset, but for 3D dataset, I just test these methods on our-collected NPC dataset, if you are interested, you can read our paper.
Best;
Xiangde.

**Comment by zs963048949** [comment]
Hi,
The results in your paper just are 3D networks. I want to compare the result between 2D and 3D semi-supervised networks for the same dataset. Are they similar for the dice under the same metric methods?
Thank you.

**Comment by Luoxd1996** [comment]
Sorry, I don't test in your mentioned experimental setting. But I think it is easy to try based on this repo.
Best;
Xiangde.

**Comment by szhang963** [comment]
Thank you.
