### ISSUE TITLE
your results 

### ISSUE THREAD

**Issue by YolandaTheCoder** [HiLab-git/SSL4MIS#13]
Thank you so much for releasing the code and dataset. Is it possible to show the performance comparison of these methods in your environment? or at least the best performance of your proposal on acdc and Brats?

**Comment by Luoxd1996** [comment]
Hi, 
Firstly, thanks for your attention. But I am so sorry, I don't enough time and GPU to do these experiments and report results, however it is easy to do this by yourself.
Best;
Xiangde.

**Comment by YolandaTheCoder** [comment]
Thank you a lot for your quick response. I am just afraid under different environment we could get different results. But since there is no comparison of these methods in a published work,  maybe it is fine I will use the results trained on my environment. Thank you again for your work.

**Comment by Luoxd1996** [comment]
Hi,
I think your concerns are very reasonable, I will provide the results on ACDC and BraTS when I have enough GPU and time. Thanks for your suggestions, if this repo is useful for your research please consider citing our works, thanks.
Best;
Xiangder.
