### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by YolandaTheCoder** [HiLab-git/SSL4MIS#14]
Hello, I preprocessed ACDC using acdc_data_processing.py and then checked my h5 file with yours by using np.allclose. It seems after patient 90 my data is different from yours some even does not match in shape for example patient 91.
May I know how exactly you processed the test set?

**Comment by YolandaTheCoder** [comment]
sorry I got it. Volume of patient 90 starts from slice 04 instead of slice 01 so I need to rename it. Sorry about the inconveniece.

**Comment by Luoxd1996** [comment]
Hi,
I am so pleased to hear that your confusion has been solved. 
Best;
Xiangde.
