### ISSUE TITLE
resampling of pancreas data

### ISSUE THREAD

**Issue by YolandaTheCoder** [HiLab-git/SSL4MIS#19]
Thank you a lot for releasing the code. Could you please also specify how to resample pancreas images to a resolution of 1.0*1.0*1.0mm? 
![image](https://user-images.githubusercontent.com/11154631/116345252-5d211f80-a81a-11eb-9867-d8772a3f65c7.png)

As we can see from the meta-info, the SliceThickness is missing from Pancreas dataset. In that case, how do you sample over Z-axis? 
By the way, Is it possible to release the data preprocessing of Pancreas-CT dataset too?

**Comment by Luoxd1996** [comment]
Hi,
Sorry, in this repo, we don't use Pancreas-CT as an example. For resampling processing, you need to learn how to use SimpleITK, which is very basic knowledge for medical image processing.
Best,
Xiangde.

**Comment by YolandaTheCoder** [comment]
Got it. By the way, did you center crop around ground truth over 3 dimension or 2 dimensions (x and y) like what has been done in UA-MT?
