### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by 18677064404** [HiLab-git/SSL4MIS#21]
Hi,

Thanks for your great work! I met some questions. 

On line 24 of file "train_uncertainty_rectified_pyramid_consistency_3D.py":from dataloaders.GTV import..., it seems that there miss the file “GTV.py”. Could you provide it ? 

Best wish!

**Comment by Luoxd1996** [comment]
Hi，
I have fixed this bug, Sorry!
Best,
Xiangde.
