### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by wyh9805** [HiLab-git/SSL4MIS#22]
Hi,

Thanks for your great work!

On line 7 of file "efficient_encoder.py":from efficientnet_pytorch import EfficientNet, it seems that there miss the file “efficientnet_pytorch.py”. Could you provide it ?

Best wish!

**Comment by Luoxd1996** [comment]
Hi,
your better install efficientnet_pytorch by yourself, it's very simple!
Best,
Xiangde!
