### ISSUE TITLE
Baidu link not working

### ISSUE THREAD

**Issue by hritam-98** [HiLab-git/SSL4MIS#25]
Hello, thanks for your nice repository, however, I tried to download the two datasets from Baidu repository but the links are not working. Can you please look into this?

**Comment by Luoxd1996** [comment]
Hi,
I tested it just now on my windows desktop, it works well. Please check your internet and software.
Best,
Xiangde.

**Comment by hritam-98** [comment]
I am talking about this link: https://pan.baidu.com/s/1CrMNP8hUExGuQNrHPuGb7w mentioned in the [Readme](https://github.com/HiLab-git/SSL4MIS/tree/master/data/BraTS2019).

**Comment by Luoxd1996** [comment]
Yeah, I know, but it works well on my desktop. So, please check your internet again.
![baidudisk](https://user-images.githubusercontent.com/19658103/131475910-5f24c146-67f1-4836-8bb8-dfeac4bb500a.png)
