### ISSUE TITLE
Problem in ACDC

### ISSUE THREAD

**Issue by hritam-98** [HiLab-git/SSL4MIS#26]
After downloading the dataset from the link provided and placing the unzipped files in ..data/ACDC folder, whenever I run any code (e.g. mean teacher/cross pseudo supervision, both in 2D), the following error occurs. However, this is not the issue in the case of BraTS2019. It works smoothly. 
![image](https://user-images.githubusercontent.com/51586842/131878430-eb2172fb-47b8-41ca-8009-1c8d9c3749ec.png)

**Comment by Luoxd1996** [comment]
Hi, 
Before running the code, you'd better read the code and readme roughly; after that, your question can be answered by yourself. In addition, I have provided the training and testing scripts you can use it.
Best,
Xiangde.

**Comment by rw1995** [comment]
> After downloading the dataset from the link provided and placing the unzipped files in ..data/ACDC folder, whenever I run any code (e.g. mean teacher/cross pseudo supervision, both in 2D), the following error occurs. However, this is not the issue in the case of BraTS2019. It works smoothly.
> ![image](https://user-images.githubusercontent.com/51586842/131878430-eb2172fb-47b8-41ca-8009-1c8d9c3749ec.png)

你把他改成 对应的数字就行了，表示有多少个样本， 他的标签是金标的
