### ISSUE TITLE
Guidance regarding semi-supervised learning

### ISSUE THREAD

**Issue by Abbas009** [HiLab-git/SSL4MIS#27]
Thanks for your code. 
I tested your code and learned a lot from it. Now I am trying to use it for other datasets for medical imaging and while implementation to one problem I am getting really bad results using the URPC method. I am new to semi-supervised learning so didn't have proper knowledge of how to train for new datasets and which hyperparameters we can tune like consistency ramp up or other training techniques. Can you suggest how to tune for others datasets?
 Secondly, if I include more unlabeled data, can it help to gain better performance than the fully supervised method? Like If I train with 100  labeled images and similar results can be obtained using 20-80 label-unlabeled settings. And If I include 50 more unlabeled data from another source can I get better performance than 100 labeled image results?

**Comment by Luoxd1996** [comment]
Hi, 
I don't know the question you meet and any information of your dataset, so I can not provided some suggestions for you. You said "I am getting really bad results using the RPC method", I am so sorry and sad, as I test it on at least four datasets, it works very well. Overall, I can't give you any suggestion, you can try other methods or design your own method.
Best,
Xiangde.
