### ISSUE TITLE
test_urpc.py

### ISSUE THREAD

**Issue by 18677064404** [HiLab-git/SSL4MIS#28]
Hi,
Is there provide a 2D "test_urpc.py".
I try to use your work:"train_uncertainty_rectified_pyramid_consistency_2D.py", but I don't know how to test it.
Thanks!

**Comment by abcxubu** [comment]
> Thanks for your reply.

Hi,
Did you successfully run the 2D 'test_urpc.py' ? I met the problem 'Traceback (most recent call last):
  File "/home/b417/xb/5_SSL4MIS-master/SSL4MIS-master/code/test_2D_fully.py", line 121, in <module>
    metric = Inference(FLAGS)
  File "/home/b417/xb/5_SSL4MIS-master/SSL4MIS-master/code/test_2D_fully.py", line 110, in Inference
    case, net, test_save_path, FLAGS)
  File "/home/b417/xb/5_SSL4MIS-master/SSL4MIS-master/code/test_2D_fully.py", line 64, in test_single_volume
    out_main, dim=1), dim=1).squeeze(0)
TypeError: softmax() received an invalid combination of arguments - got (tuple, dim=int), but expected one of:
 * (Tensor input, name dim, *, torch.dtype dtype)
 * (Tensor input, int dim, torch.dtype dtype)'. I am wondering if you know how to solve it
![1](https://user-images.githubusercontent.com/25636252/149946136-99b6e496-ab0b-4a72-9192-56b5c67f72a2.PNG)
![2](https://user-images.githubusercontent.com/25636252/149946154-30d508f5-28dd-4743-a594-22f9daa95a44.PNG)
.
