### ISSUE TITLE
which is the code for Cross Teaching between cnn and transformer

### ISSUE THREAD

**Issue by q671383789** [HiLab-git/SSL4MIS#29]
Thanks for your great work, I want to know which parts of codes are for the paper Cross Teaching between CNN and Transformer 
because there are so many train files and networks files. 
Thanks

**Comment by Luoxd1996** [comment]
Hi,
It will be released later, please stay tuned.
Best,
Xiangde.

**Comment by Luoxd1996** [comment]
Hi,
I have uploaded the implementation, please check out this [link](https://github.com/HiLab-git/SSL4MIS/blob/master/code/train_cross_teaching_between_cnn_transformer_2D.py).
Best,
Xiangde.
