### ISSUE TITLE
No module named 'val_unet_2D_dv'

### ISSUE THREAD

**Issue by hannhu** [HiLab-git/SSL4MIS#3]
Hi, I found some problem in 2ed step as following:
`Traceback (most recent call last):
  File "train_unet_2D_dv_fully_supervised.py", line 23, in <module>
    from val_unet_2D_dv import test_single_volume
ModuleNotFoundError: No module named 'val_unet_2D_dv'`
I cant find the module "val_unet_2D_dv" in your repository or pypi, How can I get it?

**Comment by hannhu** [comment]
I found the function of the same name in code/val_unet_2D.py. Is it right?

**Comment by Luoxd1996** [comment]
Hi hannhu,
Sorry, it's my fault, I have updated it just now. Please clone or pull the repo again and re-try it.
Best wishes;
Xiangde Luo.

**Comment by hannhu** [comment]
> Hi hannhu,
> Sorry, it's my fault, I have updated it just now. Please clone or pull the repo again and re-try it.
> Best wishes;
> Xiangde Luo.

thx, but get some new error 
`Traceback (most recent call last):
  File "train_unet_2D_dv_fully_supervised.py", line 225, in <module>
    train(args, snapshot_path)
  File "train_unet_2D_dv_fully_supervised.py", line 74, in train
    model = net_factory(net_type=args.model, in_chns=1, class_num=num_classes)
  File "/home/huhan/python/semi-seg/SSL4MIS/code/networks/net_factory.py", line 9, in net_factory
    net = UNet_DS(in_chns=in_chns, class_num=class_num).cuda()
  File "/home/huhan/python/semi-seg/SSL4MIS/code/networks/unet.py", line 224, in __init__
    self.decoder = Decoder_DS(params)
  File "/home/huhan/python/semi-seg/SSL4MIS/code/networks/unet.py", line 164, in __init__
    self.feature_noise = FeatureNoise()
NameError: name 'FeatureNoise' is not defined`
I cant find it's definition anywhere.

**Comment by Luoxd1996** [comment]
Hi, hannhu,
The UNet_DS is a new baseline for this project, maybe there are some bugs. I am testing these code, but limited by the GPUs, I need some time to finish it. You can use the UNet as baseline for your task or tell me these bug, I will fix it as soon as possible. After I finished these code testing, I will email you. By the way, the error of "FeatureNoise" I have fixed.
Best wishes,
Xiangde Luo.
