### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TIMAX-159** [HiLab-git/SSL4MIS#30]
![image](https://user-images.githubusercontent.com/62273225/146633859-2c07b24d-1efd-4a66-b582-c2e6f2e09425.png)
![image](https://user-images.githubusercontent.com/62273225/146633865-5dca1759-3291-47b9-bc3c-9049fe48aa7f.png)
![image](https://user-images.githubusercontent.com/62273225/146633890-03e6a867-9164-475e-8f1e-014162b05667.png)
I have tried three of the training scripts. I am pretty sure that I have downloaded all the required data and packages. Why does this constantly happen?

**Comment by Luoxd1996** [comment]
Hi,
Please check this [function](https://github.com/HiLab-git/SSL4MIS/blob/57262d08ec78db4e7925b62de27ff7ea63959a77/code/train_cross_teaching_between_cnn_transformer_2D.py#L130), before running the codebase.
Best,
Xiangde.
