### ISSUE TITLE
BRaTS2019 settings

### ISSUE THREAD

**Issue by Sun-Rider** [HiLab-git/SSL4MIS#31]
Hi,

Thanks for your fantastic work. One question is why we preprocess the BRaST2019 into a binary problem. According to your paper (https://arxiv.org/pdf/2105.09511v3.pdf), the dataset has four classes (including b.g.). Did anyone do it before? Please share the reference.

Cheers,

**Comment by Luoxd1996** [comment]
Hi, 
Thanks for your attention. You can read the original paper of the BraTS dataset and other relevant works or our lab papers. It's a common setting.
Best,
Xiangde.

**Comment by Sun-Rider** [comment]
Hi,

I've searched the BRaTS2019 related paper, and for example, in this link: https://paperswithcode.com/sota/brain-tumor-segmentation-on-brats-2019. From your paper **Medical Image Segmentation Using Squeeze-and-Expansion Transformers**, with the code for the BraTS proceeding in here:
https://github.com/askerlee/segtran/blob/462b206570d68ed10d8b98d740f6c920753d0958/code/dataloaders/brats_processing.py#L36
I think you've built four labels (including b.g.) in this approach. But I'm confused why you simply merge them together in here, 
https://github.com/HiLab-git/SSL4MIS/blob/e8c8b5c5ad36d22748ab7c5745e275f612b1186a/code/dataloaders/brats_proprecessing.py#L105.

I'm just getting confused, and could you please describe the reason for such the difference (or just simply drop me a paper link)? 

Cheers

**Comment by Luoxd1996** [comment]
Hi,
Same response, please read the original paper of the BraTS dataset in TMI 2015 carefully. 
Best,
Xiangde.

**Comment by Sun-Rider** [comment]
Hi,

Thanks for narrowing down the search region from "other relevant works or our lab papers" to the BRaTS 2015 original TMI paper; however, I'm asking for the semi-supervised approach that utilizes the binary labelled setting for the BRaTS2019 dataset (as a ref).

For anyone who also has this concern, this TMI submission:
https://arxiv.org/pdf/2112.02508.pdf
could be an example of such a semi-supervised setting.

Cheers

**Comment by Luoxd1996** [comment]
Hi, 
Again, your concern has out of the scope of this project, and this project has not a duty to provide the relevant works. Actually, the literature review is your own business, but I also provide a reference[1] for you. Finally, thanks for your attention.
[1] Shuai Chen et al. Multi-Task Attention-Based Semi-Supervised
Learning for Medical Image Segmentation, In MICCAI2019.
Best,
Xiangde.
