### ISSUE TITLE
question about adversarial_network_2D.py

### ISSUE THREAD

**Issue by JessicaChanzc** [HiLab-git/SSL4MIS#32]
Thank you for the work!

These is a quesiton I would like to ask about, I am trying to run the train_adversarial_network_2D.
I am confused about the input of DAN, which shown in the following line,
DAN_outputs = DAN(outputs_soft[args.labeled_bs:], volume_batch[args.labeled_bs:])
https://github.com/HiLab-git/SSL4MIS/blob/e8c8b5c5ad36d22748ab7c5745e275f612b1186a/code/train_adversarial_network_2D.py#L158-L159

In your code, you took the output of model(softmax **prediction**) and unlabeled **data** as input for FCDiscriminator, but would you pls tell me why? 

Thank you.

**Comment by Luoxd1996** [comment]
Hi,
I am so sorry, recently, I am too busy to reply to many issues/confusions one by one. You can modify it in your understanding or read these original papers.
Best,
Xiangde.
