### ISSUE TITLE
请问分有标签图片那里的代码是根据图片索引？

### ISSUE THREAD

**Issue by asako98** [HiLab-git/SSL4MIS#34]
![图片](https://user-images.githubusercontent.com/49807518/146861902-3f844537-e8ef-4c71-af02-6ef4c92a4ba6.png)
这里我没大看懂，dataloader是改好了，就是这里的分法我不是很懂，如果要换成自己的数据集该怎么做？
基本就这个错误
![图片](https://user-images.githubusercontent.com/49807518/146861985-2901f189-870f-45c6-b471-11f27ec3e4c7.png)

**Comment by Luoxd1996** [comment]
Hi,
您可以删掉这个不要就行，然后改一下dataloader。
祝好，
罗。

**Comment by asako98** [comment]
> Hi, 您可以删掉这个不要就行，然后改一下dataloader。 祝好， 罗。
![image](https://user-images.githubusercontent.com/49807518/146868354-4e8ee822-42d5-4d22-83c5-dfbc6baa64da.png)
你好，我改成这样，但是还是会报错，是dataloader的问题还是？
![image](https://user-images.githubusercontent.com/49807518/146868430-22cea4d2-0fe3-4add-b4c7-fd541bf0bcdd.png)

**Comment by Luoxd1996** [comment]
hi,
您要根据需要修改一些东西，您先大概看懂代码吧，然后根据报错去修复问题就行，您这样的描述我也不太可能一行一行帮您debug。
祝好，
罗。

**Comment by asako98** [comment]
> hi, 您要根据需要修改一些东西，您先大概看懂代码吧，然后根据报错去修复问题就行，您这样的描述我也不太可能一行一行帮您debug。 祝好， 罗。

你好，实在不好意思..我改了好久，traindataset和valdataset看上去应该是读进去了，但是发生了这样的错误
![图片](https://user-images.githubusercontent.com/49807518/146897505-86376180-0db6-49c6-bbf2-938d73378b66.png)
我的dataset就改了这几块地方
![图片](https://user-images.githubusercontent.com/49807518/146897647-821739a9-e0b5-46b6-8f20-2d240c999d54.png)
![图片](https://user-images.githubusercontent.com/49807518/146897725-60acb63d-c5b6-4fdc-a4ae-0acf1205e645.png)
以及改了这块地方
![图片](https://user-images.githubusercontent.com/49807518/146897812-0866dd9e-bf5c-4270-b8e2-1f6bf6acd9b6.png)
其余都没有改动，实在麻烦了。。我查了很多也解决不了

**Comment by asako98** [comment]
> hi, 您要根据需要修改一些东西，您先大概看懂代码吧，然后根据报错去修复问题就行，您这样的描述我也不太可能一行一行帮您debug。 祝好， 罗。
你好我解决了这个问题，但是运行过程中又出现了这个问题
![图片](https://user-images.githubusercontent.com/49807518/146935682-36ece96d-3133-4cd4-8cc5-0ff06098cf92.png)
我之前遇到过这类问题，是因为输出的标签数不对，我感觉您的softmax其实能解决，但报错了，我尝试了用sigmod，也不行
![图片](https://user-images.githubusercontent.com/49807518/146935892-9733e132-1633-4212-b464-956002f25e34.png)
我print了inputsize和targetsize ,结果是相同的，都是1通道（我输入三通道，输出一通道）
![图片](https://user-images.githubusercontent.com/49807518/146936044-173098cd-5b90-4942-9c58-fe13e6b06f7d.png)
所以我不太明白为什么会这样，而且我发现输出num_classes改成2居然能跑，但是第二个epoch就报错了，而且打印的inputsize和targetsize 居然变成2通道....然后报这样的错
我的数据集img是三通道，label是一通道的二值图
