### ISSUE TITLE
Miss test file

### ISSUE THREAD

**Issue by jelly571** [HiLab-git/SSL4MIS#38]
Hi,
Thank you very much for sharing your work, but I do not find the test file for ' Cross Teaching between CNN and Transformer'. Is it convenient for you to upload the test file? Thanks again.
good luck

**Comment by Luoxd1996** [comment]
Hi,
Yes, I will upload the test file later.
Best,
Xiangde

**Comment by geek-APTX4869** [comment]
Use CNN or transformer weights for testing？
