### ISSUE TITLE
A paper is linked incorrectly

### ISSUE THREAD

**Issue by Moeo3** [HiLab-git/SSL4MIS#39]
Hello. The link to the paper Contrastive Semi-Supervised Learning for 2D Medical Image Segmentation by P. Pandey and Mausam published on miccai2021 has expired. The currently available Arxiv link is: https://arxiv.org/pdf/2106.06801v1.pdf

**Comment by Luoxd1996** [comment]
Hi,
Thanks for your suggestion, I have fixed this issue.
Best,
Xiangde.
