### ISSUE TITLE
Great project, I have a question about About the cross teaching between CNN and Transformer paper.

### ISSUE THREAD

**Issue by Byronnar** [HiLab-git/SSL4MIS#41]
```
Table 2: Mean 3D DSC and HD95 (mm) on the ACDC dataset. All results are based on
the same backbone (UNet) with a fixed seed. Mean and standard variance (in
parentheses) are presented in this table. Red numbers denote the p-value < 0.05
based on paired t-test when comparing with the others
```
How to get the Mean and standard variance (in parentheses) are presented in this table? And how to generate the Red numbers denote the p-value < 0.05 based on paired t-test when comparing with the others? Could your please share the code? Thank you. 
@Luoxd1996 Looking forward to your reply.

**Comment by Luoxd1996** [comment]
Hi,
Firstly, the mean and standard variance values have been calculated in the test stage. Secondly, the paired t-test result can be calculated by scipy.stats.ttest_ind API.
Best,
Xiangde.

**Comment by Byronnar** [comment]
> 

Thanks for your reply. Could you please give a example? In the test stage I can not find the code to calculate the mean and standard variance values.. And what are the paired t-test inputs? Thank you.

**Comment by Byronnar** [comment]
@Luoxd1996
