### ISSUE TITLE
paper date on "Shape-aware Multi-task Learning for Semi-supervised 3D Medical Image Segmentation"

### ISSUE THREAD

**Issue by jizongFox** [HiLab-git/SSL4MIS#44]
Hello, 

I just noticed that the paper you added recently "Shape-aware Multi-task Learning for Semi-supervised 3D Medical Image Segmentation" was the one that appeared one year ago. I am wondering whether it would be better to order the articles by their post date instead of the accepted date. 

Best,

**Comment by Luoxd1996** [comment]
Hi, Dr. Peng; 
Thanks for your suggestion, I will re-order the paper list by their open data carefully. BTW, the paper "Shape-aware Multi-task Learning for Semi-supervised 3D Medical Image Segmentation" (accepted by BIBM2022) is different from "Shape-aware Semi-supervised 3D Semantic Segmentation for Medical Images" (accepted by MICCAI2021), the BIBM paper doesn't present in the Arxiv (I am not sure).
Best,
Xiangde.
