### ISSUE TITLE
models

### ISSUE THREAD

**Issue by heixinbaicaishang** [HiLab-git/SSL4MIS#46]
I installed all the moudels, but the model still has the problem that models are not defined. I have tried many methods. When I input from torchvision import models, the problem is solved, but this problem occurs again? How to solve it?
![image](https://user-images.githubusercontent.com/92560728/156590036-75397013-00b3-45ae-83ec-c7d5e321276c.png)
![image](https://user-images.githubusercontent.com/92560728/156590119-a3076466-1b92-4207-bcc3-340f7267debd.png)
![image](https://user-images.githubusercontent.com/92560728/156590190-50fa1ba8-5c2c-4b07-a038-15c11d1be113.png)

**Comment by Luoxd1996** [comment]
Hi,
The error information has shown the details of the bug, you just need to fix it. It's easy.
Best,
Xiangde.

**Comment by heixinbaicaishang** [comment]
Thank you, I got it, I need to add an __init__.py to the networks file. If you have the same problem as me, you can make such changes.

**Comment by heixinbaicaishang** [comment]
Thanks to the author, your hard work enabled us to use the semi-supervised learning code. My classmates and I are using your code for medical image segmentation. Thank you again and wish you a happy life.

**Comment by Luoxd1996** [comment]
Hi,
You are welcome, I am very happy to hear that this project can help your
and your friends' research. If you used it for your publications, please
consider citing our works. Thanks!
Best,
Xiangde.

heixinbaicaishang ***@***.***> 于2022年3月4日周五 19:52写道：
