### ISSUE TITLE
Relevant Paper or description for the BraTs experiments

### ISSUE THREAD

**Issue by lemoshu** [HiLab-git/SSL4MIS#5]
Hi,

Thanks for your great work!
I would like to know if there are some relevant description or paper for the BraTs dataset preprocessing setting?

Thanks,
Jack

**Comment by Luoxd1996** [comment]
Hi, Jack;
Yes, there are many papers about the BraTS challenge dataset preprocessing setting, you can just search the keyword "BraTS" from google scholar, you can find many papers. By the way, the second winner's code in BraTS2017 can be found at: https://github.com/taigw/brats17.
Best wishes;
xdluo.
