### ISSUE TITLE
Input of 3D semi-supervised medical image segmentation

### ISSUE THREAD

**Issue by kimjisoo12** [HiLab-git/SSL4MIS#50]
Hello, I have seen many semi-supervised segmentation models of 3D medical images recently, and found that almost all the data sets used are 2018LA and the input format is H5 file. I would like to know whether the input is niI format, or whether the current 3D semi-supervised medical image segmentation can only use H5 input。thanks

**Comment by Luoxd1996** [comment]
Hi,
The input type is numpy array or pytorch tensor, so you can store your data in any data file, and then read them into array or tensor for the network training.
Best,
Xiangde.
