### ISSUE TITLE
transforms 对label操作，semi-supervise大多数数据unlabel

### ISSUE THREAD

**Issue by Factoryfromhere** [HiLab-git/SSL4MIS#52]
train_mean_teachers_3D + BraTs2019，Dataset默认将所有数据的image和label都读入了，实际semi-supervise大多数数据unlabel，后面的transform也是作用于label

**Comment by Luoxd1996** [comment]
您好，请您仔细阅读代码，计算损失函数包括diceh和ce，[here](https://github.com/HiLab-git/SSL4MIS/blob/9cb4b3c6c4c904bf35af5a607b7af851c88310db/code/train_cross_teaching_between_cnn_transformer_2D.py#L230). 哪里用到了没有labeled数据的label了？label_batch[:args.labeled_bs] 指的是仅考虑标注数据标签，无标注数据是标签[pseudo_sup](https://github.com/HiLab-git/SSL4MIS/blob/9cb4b3c6c4c904bf35af5a607b7af851c88310db/code/train_cross_teaching_between_cnn_transformer_2D.py#L235).

**Comment by Factoryfromhere** [comment]
loss没什么问题，数据处理这块，比如brants2019.py里面这个函数：就对label做了操作
![image](https://user-images.githubusercontent.com/44833391/162858724-70501401-ddcd-418e-9051-1436591e2c34.png)
