### ISSUE TITLE
About URPC Training On Brats2019

### ISSUE THREAD

**Issue by QUIvannn** [HiLab-git/SSL4MIS#60]
Hi,
Good work and thanks for the scripts, it's good to use.
I've trained a URPC model on brats2019 dataset by using this script in `train_brats2019_semi_seg.sh` :
`python -u train_uncertainty_rectified_pyramid_consistency_3D.py --labeled_num 25 --total_num 250 --root_path ../data/BraTS2019 --max_iterations 30000 --base_lr 0.1 --exp BraTS2019/Uncertainty_Rectified_Pyramid_Consistency`
but the result is poor:
![7073ed15471621f7adacf3146f4f268](https://user-images.githubusercontent.com/72849757/183079952-cffe8563-39e3-49f4-968d-9ba5dc9c3978.png)
The dice_score is 0.41 not like what the paper says (about 0.8).
While it's OK on ACDC dataset (the dice_score is high enough and hd95 is low enough).
Is anything wrong?

**Comment by Luoxd1996** [comment]
Hi,
So strange, I ran the experiment again, and there were some differences in results, but the differences were minor (<1%). But your results are too different, and I also don't know why :|).
Best,
Xiangde.

**Comment by QUIvannn** [comment]
> Hi, So strange, I ran the experiment again, and there were some differences in results, but the differences were minor (<1%). But your results are too different, and I also don't know why :|). Best, Xiangde.

Thanks for response.
Did you also run the same script? Maybe there are some differences about parameters in train file (I've done nothing on it since I downloaded them)? Could you share them with me? I'll be appreciated.

**Comment by QUIvannn** [comment]
It seems that the `num_classes` parameter has been set to wrong number. Setting it to 2 can solve the problem. Thanks for the supports anyway.
