### ISSUE TITLE
How can we download the datasets? 

### ISSUE THREAD

**Issue by PotatoThanh** [HiLab-git/SSL4MIS#65]
Hi, I tried to download the datasets but it requires  a bidu account. However, I can't register account with foreign mobile number ,and don't know much Chinese. Can you provide Google Drive, Dropbox or other download link? Thanks!

**Comment by Luoxd1996** [comment]
Hi,
This is the download link (Google Drive): https://drive.google.com/drive/folders/1XJgSKlR58iGTrWjvlJBOZH73NaempGV5?usp=sharing.
Best,
Xiangde.

**Comment by PotatoThanh** [comment]
Thank you!

**Comment by PotatoThanh** [comment]
Thank you!
