### ISSUE TITLE
What is the unet_2D_dv？

### ISSUE THREAD

**Issue by zs963048949** [HiLab-git/SSL4MIS#7]
Could you tell me which paper the concept of "unet_2D_dv" come from?

**Comment by Luoxd1996** [comment]
Hi, 
It means deep supervised network, you can  search the deep supervised network in Google Scholar to learn more details.
Best wishes;
xdluo.

**Comment by zs963048949** [comment]
> Hi,
> It means deep supervised network, you can search the deep supervised network in Google Scholar to learn more details.
> Best wishes;
> xdluo.

Thanks！！！
