### ISSUE TITLE
Why is the batch size of labeled data equal to the one of unlabeled data?

### ISSUE THREAD

**Issue by zs963048949** [HiLab-git/SSL4MIS#8]
Whether can I set the batch size of unlabeled data 3 times with the batch size of labeled data? What is different between them?Thank you for your answer !!!

**Comment by Luoxd1996** [comment]
Hi, 
Sorry, I don't know, I also want to know the reason, if you find the answer please let me know, thanks. But, also most existing works have used this setting, maybe you can try any combination for better results.
Best wishes,
xdluo.
